---
#
# Ansible managed
#
repository:
  description: Install and configure CUPS, the Common Unix Printing System.
  homepage: https://robertdebock.nl/
  topics: cups, print, printer, printing, ansible, molecule, tox, playbook
