---
# tasks file for cups

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install packages
  ansible.builtin.package:
    name: cups
    state: present

- name: Configure cups
  ansible.builtin.template:
    src: cupsd.conf.j2
    dest: /etc/cups/cupsd.conf
    mode: "0640"
    validate: cupsd -t -s /etc/cups/cups-files.conf -c %s
  notify:
    - Restart cups

- name: Start and enable software
  ansible.builtin.service:
    name: "{{ cups_service }}"
    state: started
    enabled: yes
